### ISSUE TITLE
Error trying to run Metaworld environment

### ISSUE THREAD

**Issue by varunagrawal** [siddhanthaldar/FISH#3]
I am trying to run the Metaworld benchmark as the simulation environment since we don't have access to the same robots. On running the below command, we get the following error:

```sh
python train_robot.py agent=bc suite=metaworld  num_demos=2
```

```bash
workspace: /Users/varunagrawal/FISH-Workspace/FISH/FISH/exp_local/2024.03.30/050345_exp_metaworld_pixels_drawer-close-v2_seed_2
Error executing job with overrides: ['agent=bc', 'suite=metaworld', 'num_demos=2']
Traceback (most recent call last):
  File "/Users/varunagrawal/.pyenv/versions/3.10.12/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 347, in make
    env = RGBArrayAsObservationWrapper(env, ml1, max_path_length=MAX_PATH_LENGTH[name], camera_name=CAMERA[name])
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 51, in __init__
    dummy_obs = self.get_frame()
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 118, in get_frame
    frame = self._env.render(offscreen=True, camera_name=self.camera_name)
TypeError: MujocoEnv.render() got an unexpected keyword argument 'offscreen'
```

I can't find anything about the parameters `offscreen` and `camera_name` in the Mujoco documentation, and it fails to work for both Mujoco version 2.3.7 and 3.1.3.
On removing the parameters, I get the error

```bash
Error executing job with overrides: ['agent=bc', 'suite=metaworld', 'num_demos=2']
Traceback (most recent call last):
  File "/Users/varunagrawal/.pyenv/versions/3.10.12/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 364, in make
    env = RGBArrayAsObservationWrapper(env,
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 58, in __init__
    dummy_obs = self.get_frame()
  File "/Users/varunagrawal/FISH-Workspace/FISH/FISH/suite/metaworld.py", line 128, in get_frame
    frame = self._env.render()
  File "/Users/varunagrawal/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 409, in render
    return self.mujoco_renderer.render(
  File "/Users/varunagrawal/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 646, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/Users/varunagrawal/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 688, in _get_viewer
    raise AttributeError(
AttributeError: Unexpected mode: None, expected modes: human, rgb_array, or depth_array

The above exception was the direct cause of the following exception:
```

Moreover, I have downloaded the expert demonstrations for Metaworld, but the README doesn't specify where to place them.
Can you please provide more detailed instructions on how to get the example up and running?

On a more general case, I would like to understand what is happening in terms of the `gym` environments. I may not be familiar with this, but are you using the gym environments as a sort of virtual world for your real robot setup? My understanding of the code seems to indicate that code for the Hello, Allegro and xARM are all developed to operate on the real robot hardware, so how the `gym` environments fit in is a bit of a mystery to me.

@siddhanthaldar @jyopari tagging for attention.

**Comment by NNNatsuki** [comment]
I have encountered the same problem as you. Have you solved it?

**Comment by siddhanthaldar** [comment]
Hi,

Apologies for not responding earlier. This issue has resulted from changes in Metaworld since this work was released. An easy way to fix this would be to set up Metaworld using our newer work, [BAKU](https://github.com/siddhanthaldar/BAKU/tree/main).

Regarding the gym environments, you are correct that we use `gym` as an interface to create environments for the real robot similar to existing simulation environments (with reset, step and render functionalities). This allows us to use similar `suite` scripts for the simulation and real environments.

Hope this helps! Let me know if you have any other questions.
